function evenFibSum = project2(sumLimit)
% projecteuler - Even Fibonacci Numbers: Each new term in the Fibonacci 
% sequence is generated by adding the previous two terms. By starting 
% with 1 and 2, the first 10 terms will be:
%     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% By considering the terms in the Fibonacci sequence whose values do not 
% exceed four million, find the sum of the even-valued.
%
% Test 1: for x = 4000000 y = 4613732
% Test 2: for x = 97455000 y = 82790070
%
    tic;
    %
    n = 1;
    fibN = 1;
    fibSum = 0;
    while fibN < sumLimit
        if mod(fibN, 2) == 0
            fibSum = fibSum + fibN;
        end
        n = n + 1;
        fibN = fibonacciIterative(n);
    end
    %
    evenFibSum = fibSum;
    fprintf('%d is the sum of a Fibonacci sequence''s terms with maximum value less than %d. \n \n', evenFibSum, sumLimit);
    %
    toc;
end
%
function F = fibonacciIterative(n)
    first  = 0;
    second = 1;
    third  = 0;
    for ii = 1:n
        third = first + second;
        first = second;
        second = third;
    end
    F = first;
end

