function project29
% projecteuler 29 - Distinct Powers: This function computes
% the number of terms in a numerically-ordered sequence
% generated by a^b for 2 <= a <= 100 and 2 <= b <= 100.
%
tic; % Start elapsed time timer
%
rawResults = zeros(99,99); % The maximum number to terms is ~99*99
for aBase = 2:100
    for bExponent = 2:100
        rIndex = aBase - 1;
        cIndex = bExponent - 1;
        rawResults(rIndex, cIndex) = aBase^bExponent;
    end % for bExponent
end % for aBase
%
rowArray = reshape(rawResults, 1, []);             % Reshape square matrix into linear array
distinctNumber = length(unique(rowArray)); % Get length of array of unique elements
%
fprintf('For 2 <= a <= 100 and 2 <= b <= 100 the number of distinct terms generated by the function a^b is %d. \n\n', distinctNumber);
%
toc; % Stop elapsed time timer and print the results
end

